In [ ]:
import pandas as pd

In [ ]:
!pip install kaggle

In [ ]:
# Perguntas principais a fazer a partir do dataset:
# 1. Qual curso têm mais desempenho de horas de estudo por dia? 
# 2. Quais cursos têm a media geral mais alta? 
# 3. Alunos de Alto Desempenho ou "Alunos em Risco?

In [ ]:
from kaggle.api.kaggle_api_extended import KaggleApi
   
api = KaggleApi()
api.authenticate()
   
api.dataset_download_files('jayjoshi37/Student_data', 
                               unzip=True)

In [4]:
import os
os.chdir('C:/Users/ricar/Documents')

import pandas as pd
df = pd.read_csv('Student_data.csv')
df.head()

,Student_ID,Gender,Age,Major,Attendance_Pct,Study_Hours_Per_Day,Previous_GPA,Sleep_Hours,Social_Hours_Week,Final_CGPA
0,ID00001,Male,20,Engineering,83.9,4.4,2.65,9.1,8,2.78
1,ID00002,Female,24,Business,80.7,4.0,3.58,4.0,4,3.76
2,ID00003,Female,20,Mathematics,91.5,3.9,3.29,6.7,4,3.75
3,ID00004,Female,23,Engineering,73.9,8.8,3.48,4.0,6,3.69
4,ID00005,Male,21,Economics,79.8,2.2,2.66,8.7,6,2.34

In [5]:
# lista todas os arquivos dentro de documents:
import os
os.listdir()

['- Depoimento que eu darei sobre minha trajetória como uma ex-homeschooler..pdf',
 'AMANDA - 15 ANOS',
 'Amanda Festa 15 anos - 2025.zip',
 'BANCO DE DADOS-20251126T222913Z-1-001.rar',
 'carta ana IV.zip',
 'carta em espanhol - ANA E LINDA.pdf',
 'comprovante_amanda_eeman.pdf',
 'Cronograma Semestral Faculdade - Linda M..pdf',
 'Currículo (1) (3).pdf',
 'daily_internet_usage_by_age_group.csv',
 'desktop.ini',
 'ensaio Linda 17 anos 2025_01.zip',
 'exercício Nisston Windows.txt',
 'Friend Letter VI.pdf',
 'IHC- AULA 06 - DOCUMENTO - NOTAS DE AULA.pdf',
 'index.curriculo.html',
 'Introduction_to_Cybersecurity_certificate_lindamariasmelo-gmail-com_18bc1a30-f794-402c-be80-bb76869a8333.pdf',
 'linda 2025_02.zip',
 'Lista de Exercícios - Sistemas Operacionais.pdf',
 'Meus Vídeos',
 'Minhas Imagens',
 'Minhas Músicas',
 'plano_lazer.docx',
 'PROJETO2_GLAUCIO teste',
 'Projeto2_JavaFernanda',
 'ProjetoP2',
 'PROJETO_1AVALIAÇÃO_GLÁUCIO',
 'Projeto_Final_Frontend (atual)',
 'Projeto_LP1-master',
 'Projeto_LP1_Farmacia',
 'pycharm',
 'python',
 'Student_data.csv']

In [6]:
# Informações sobre o dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Student_ID           5000 non-null   object
 1   Gender               5000 non-null   object
 2   Age                  5000 non-null   int64
 3   Major                5000 non-null   object
 4   Attendance_Pct       5000 non-null   float64
 5   Study_Hours_Per_Day  5000 non-null   float64
 6   Previous_GPA         5000 non-null   float64
 7   Sleep_Hours          5000 non-null   float64
 8   Social_Hours_Week    5000 non-null   int64
 9   Final_CGPA           5000 non-null   float64
dtypes: float64(5), int64(2), object(3)
memory usage: 390.8+ KB

In [7]:
# Estatísticas descritivas
df.describe()

,Age,Attendance_Pct,Study_Hours_Per_Day,Previous_GPA,Sleep_Hours,Social_Hours_Week,Final_CGPA
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,20.948600,83.795740,4.517840,3.093824,7.012060,8.006400,3.272224
std,2.017417,12.867904,2.568104,0.476754,1.424377,2.797771,0.507954
min,18.000000,26.200000,0.100000,1.350000,4.000000,0.000000,1.160000
25%,19.000000,75.100000,2.600000,2.760000,6.000000,6.000000,2.920000
50%,21.000000,85.050000,4.000000,3.100000,7.000000,8.000000,3.310000
75%,23.000000,94.800000,6.000000,3.430000,8.000000,10.000000,3.680000
max,24.000000,100.000000,14.000000,4.000000,10.000000,20.000000,4.000000

In [77]:
# Como ler os dados acima?

# count - quantas linhas contém dados (500 alunos)
# mean - média dos valores. A média de Studt_Hours_Per_Day é de 4.5h por dia.
# std - é o desvio padrão, ou seja, o quanto os valores variam.
# min - é o menor valor encontrado. Ou seja, O menor valor de Sleep_Hours é de 4h. O menor valor de Study_Hours_Per_Day é de 0.1h por dia.
# 25%, 50%, 75% - são os quartis. Como os dados são distribídos. Por exemplo, 50% das pessoas estudam 4h por dia. 
# max - é o maior valor encontrado. Ou seja, há 4 maiores final_CGPA.

In [79]:
# Agora vou começar a brincar usando pandas -> operações básicas, groupby, merge, pivot tables:

In [80]:
# Agora vou filtrar pessoas menores que 23 anos - linhas

df[df['Age'] < 23]

,Student_ID,Gender,Age,Major,Attendance_Pct,Study_Hours_Per_Day,Previous_GPA,Sleep_Hours,Social_Hours_Week,Final_CGPA
0,ID00001,Male,20,Engineering,83.9,4.4,2.65,9.1,8,2.78
2,ID00003,Female,20,Mathematics,91.5,3.9,3.29,6.7,4,3.75
4,ID00005,Male,21,Economics,79.8,2.2,2.66,8.7,6,2.34
5,ID00006,Male,20,Business,86.8,3.5,2.16,7.0,7,2.41
6,ID00007,Male,22,Mathematics,77.5,3.6,2.66,8.7,5,2.69
...,...,...,...,...,...,...,...,...,...,...
4994,ID04995,Male,18,Economics,98.5,3.8,2.88,5.8,7,3.11
4996,ID04997,Male,20,Economics,82.8,7.2,3.12,7.6,7,3.70
4997,ID04998,Male,19,Engineering,92.2,13.5,3.55,6.3,6,4.00
4998,ID04999,Female,22,Computer Science,100.0,2.4,2.86,7.0,6,2.93
4999,ID05000,Female,20,Mathematics,86.5,7.4,2.49,7.8,4,3.07

In [76]:
# Estudantes que passam menos de 5 horas dormindo.

df[df['Sleep_Hours'] < 5]

,Student_ID,Gender,Age,Major,Attendance_Pct,Study_Hours_Per_Day,Previous_GPA,Sleep_Hours,Social_Hours_Week,Final_CGPA
1,ID00002,Female,24,Business,80.7,4.0,3.58,4.0,4,3.76
3,ID00004,Female,23,Engineering,73.9,8.8,3.48,4.0,6,3.69
34,ID00035,Female,20,Computer Science,80.9,2.2,3.59,4.2,10,3.85
39,ID00040,Male,19,Computer Science,79.4,6.6,2.96,4.8,4,3.07
40,ID00041,Male,21,Business,99.7,4.8,2.96,4.1,10,3.05
...,...,...,...,...,...,...,...,...,...,...
4957,ID04958,Female,20,Mathematics,45.9,6.3,3.35,4.8,9,2.93
4960,ID04961,Male,18,Engineering,100.0,1.8,3.38,4.5,9,3.61
4975,ID04976,Male,21,Psychology,73.2,6.3,3.21,4.8,9,3.31
4978,ID04979,Male,19,Psychology,89.3,7.5,2.68,4.5,6,2.96
4983,ID04984,Female,22,Mathematics,100.0,3.9,3.12,4.4,5,3.56

In [75]:
# Estudantes de gênero feminino.

df_filtered = df[(df['Gender'] == 'Female')]
df_filtered.head() # pode-se tirar o head, assim vai aparecer mais opções

,Student_ID,Gender,Age,Major,Attendance_Pct,Study_Hours_Per_Day,Previous_GPA,Sleep_Hours,Social_Hours_Week,Final_CGPA
1,ID00002,Female,24,Business,80.7,4.0,3.58,4.0,4,3.76
2,ID00003,Female,20,Mathematics,91.5,3.9,3.29,6.7,4,3.75
3,ID00004,Female,23,Engineering,73.9,8.8,3.48,4.0,6,3.69
7,ID00008,Female,20,Psychology,95.0,4.7,3.44,7.4,4,3.76
8,ID00009,Female,22,Computer Science,100.0,4.3,4.00,5.0,12,4.00

In [40]:
# Contar todos os Females and Male:

df['Gender'].value_counts()    # Sabia que existem mais homens do que mulheres nesse mundo?

Gender
Male      2748
Female    2252
Name: count, dtype: int64

In [44]:
# - - - - - - - - - - - - - - -
#     Usando o groupyby!
# - - - - - - - - - - - - - - -

In [74]:
# Média da Final CGPA pela Previous GPA

df.groupby('Final_CGPA') ['Previous_GPA'].mean()

Final_CGPA
1.16    1.350000
1.43    2.100000
1.46    1.590000
1.53    1.930000
1.57    1.690000
          ...
3.96    3.606842
3.97    3.678421
3.98    3.818824
3.99    3.641765
4.00    3.794471
Name: Previous_GPA, Length: 229, dtype: float64

In [73]:
# Linha específica & coluna específica

df.loc[0, 'Age']      # Resposta = 20.

np.int64(20)

In [72]:
# Filtrando + selecionando apenas algumas colunas - menor que 20 anos nas colunas a seguir.

df.loc[df['Age'] < 20, ['Age', 'Major', 'Social_Hours_Week']]

      Age             Major  Social_Hours_Week
15     19       Mathematics                 11
20     18       Engineering                  7
25     18        Psychology                 12
26     19  Computer Science                  9
29     18        Psychology                  7
...   ...               ...                ...
4978   19        Psychology                  6
4986   18        Psychology                  9
4991   18  Computer Science                 11
4994   18         Economics                  7
4997   19       Engineering                  6

[1518 rows x 3 columns]

In [71]:
# criando uma variável  que filtra a média das horas de estudo maiores que 4h e meia.

high_study = df.groupby('Major').filter(lambda x: x['Study_Hours_Per_Day'].mean() > 4.5)
high_study.head()  # pode-se tirar head, assim vai aparecer mais resultados.

# lambda é uma forma rápida e prática de fazer funções anônimas

,Student_ID,Gender,Age,Major,Attendance_Pct,Study_Hours_Per_Day,Previous_GPA,Sleep_Hours,Social_Hours_Week,Final_CGPA
1,ID00002,Female,24,Business,80.7,4.0,3.58,4.0,4,3.76
4,ID00005,Male,21,Economics,79.8,2.2,2.66,8.7,6,2.34
5,ID00006,Male,20,Business,86.8,3.5,2.16,7.0,7,2.41
8,ID00009,Female,22,Computer Science,100.0,4.3,4.00,5.0,12,4.00
9,ID00010,Female,24,Economics,73.7,4.1,2.89,5.5,3,3.01

In [69]:
#Em vez de usar apenas .sum(), usar .agg() para aplicar *funções* diferentes a colunas diferentes e renomeá-las simultaneamente;

df.groupby('Student_ID').agg(
    Study_Hours_Per_Day= ('Study_Hours_Per_Day','sum'), # vai realisar a função de somar
    Age=('Age', 'mean'),                                # vai realisar a função média
    Sleep_Hours=('Sleep_Hours', 'count')                # vai realisar a função de contar
    
    
)

            Study_Hours_Per_Day   Age  Sleep_Hours
Student_ID
ID00001                     4.4  20.0            1
ID00002                     4.0  24.0            1
ID00003                     3.9  20.0            1
ID00004                     8.8  23.0            1
ID00005                     2.2  21.0            1
...                         ...   ...          ...
ID04996                     2.4  23.0            1
ID04997                     7.2  20.0            1
ID04998                    13.5  19.0            1
ID04999                     2.4  22.0            1
ID05000                     7.4  20.0            1

[5000 rows x 3 columns]

In [97]:
# POR FIM:

# Perguntas principais a fazer a partir do dataset:
# 1. Qual curso têm mais desempenho de horas de estudo por dia? 
# 2. Qual curso têm a media geral (gpa) mais alta? 
# 3. Qual gênero predomina na grande maioria dos cursos?

In [89]:
# 1. RESPOSTA:
# criando uma variável  que filtra o cruso com a maior média de horas de estudo.

curso_vencedor = df.groupby('Major')['Study_Hours_Per_Day'].mean().idxmax()
print(f'O curso vencedor com a maior média de horas de estudo foi: {curso_vencedor}')

# Mas qual foi o valor da média máxima? Aqui a resposta:
media_maxima = df.groupby('Major')['Study_Hours_Per_Day'].mean().max()
print(f"O valor da maior média do curso com o maior tempo de estudo foi: {media_maxima}")

O curso vencedor com a maior média de horas de estudo foi: Economics
O valor da maior média do curso com o maior tempo de estudo foi: 4.6202395209580835

In [95]:
# 2. RESPOSTA:

maior_gpa = df.groupby('Major')['Final_CGPA'].mean().idxmax()
print(f'O curso com a média de nota final do GPA mais alta foi: {maior_gpa}')

# Tá, mais qual o valor final desse cálculo da média mais alta? Aqui:
maior_media = df.groupby('Major')['Final_CGPA'].mean().max()
print(f"O valor da media mais alta foi de: {maior_media}")

O curso com a média de nota final do GPA mais alta foi: Computer Science
O valor da media mais alta foi de: 3.304188679245283

In [101]:
# 3. RESPOSTA:

genero_por_curso = df.groupby(['Major', 'Gender']).size().unstack()  # Unstack é como "desempilhar" um nível de linhas (index) e transformá-lo em colunas.
print(genero_por_curso)

# Qual gênero vence em mais cursos?
genero_dominante = genero_por_curso.idxmax(axis=1)                   # axis significa: indica a direção ao longo da qual uma operação será aplicada. axis=1 → opera ao longo das colunas (ou seja, a função é aplicada por linha). Ou seja, "atravessa" pelas colunas (horizontal).

print("\nGênero dominante por curso:")
print(genero_dominante)

# Vencedor final:
vencedor_geral = genero_dominante.value_counts().idxmax()            # Values_count significa: o resultado vem ordenado em ordem decrescente de frequência.
print(f"\nNo geral, o gênero predominante na maioria dos cursos é: {vencedor_geral}")

Gender            Female  Male
Major
Business             374   469
Computer Science     367   428
Economics            348   487
Engineering          351   448
Mathematics          389   470
Psychology           423   446

Gênero dominante por curso:
Major
Business            Male
Computer Science    Male
Economics           Male
Engineering         Male
Mathematics         Male
Psychology          Male
dtype: object

No geral, o gênero predominante na maioria dos cursos é: Male

#                                              FORMAS DE ESCREVER USANDO O MARKDOWN JUPYTER:
# Relatando descobertas aqui
## Relatando fatos aqui
*italico vibe testing*
**negrito test**
- listas
1. listas
[texto_link]
(url de site)
($E = mc^2$)
# ACIMA | Imagens, tabelas, fórmulas matemáticas com LaTeX, etc.

# Para dar um play e aparecer de fato, esses exemplos de texto acima, basta dar dois cliques nessa célula. Para voltar ao normal também.